export const contactListExample = [
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User 45g43g45g45g45g45g45g45",
    msg: "Hello There Hello There",
    status: "away",
  },
  {
    email: "email@mail.com",
    name: "User Blg4g45g54g45g45gah",
    msg: "Hello There Hello There Hello There Hello There Hello There",
    status: "blocked",
  },
  {
    email: "email@mail.com",
    name: "User B54g245glah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There Hello There Hello There Hello There Hello There",
    status: "busy",
  },
  {
    email: "email@mail.com",
    name: "User Bl54g45gah",
    msg: "Hello There Hello There Hello There Hello There",
    status: "offline",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There",
    status: "inactive",
  },
  {
    email: "email@mail.com",
    name: "User B54g45gah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User 45g43g45g45g45g45g45g45",
    msg: "Hello There Hello There",
    status: "away",
  },
  {
    email: "email@mail.com",
    name: "User Blg4g45g54g45g45gah",
    msg: "Hello There Hello There Hello There Hello There Hello There",
    status: "blocked",
  },
  { name: "User B54g245glah", msg: "Hello There", status: "online" },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There Hello There Hello There Hello There Hello There",
    status: "busy",
  },
  {
    email: "email@mail.com",
    name: "User Bl54g45gah",
    msg: "Hello There Hello There Hello There Hello There",
    status: "offline",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There",
    status: "inactive",
  },
  {
    email: "email@mail.com",
    name: "User B54g45gah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There",
    status: "inactive",
  },
  {
    email: "email@mail.com",
    name: "User B54g45gah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User 45g43g45g45g45g45g45g45",
    msg: "Hello There Hello There",
    status: "away",
  },
  {
    email: "email@mail.com",
    name: "User Blg4g45g54g45g45gah",
    msg: "Hello There Hello There Hello There Hello There Hello There",
    status: "blocked",
  },
  {
    email: "email@mail.com",
    name: "User B54g245glah",
    msg: "Hello There",
    status: "online",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There Hello There Hello There Hello There Hello There",
    status: "busy",
  },
  {
    email: "email@mail.com",
    name: "User Bl54g45gah",
    msg: "Hello There Hello There Hello There Hello There",
    status: "offline",
  },
  {
    email: "email@mail.com",
    name: "User Blah",
    msg: "Hello There Hello There",
    status: "inactive",
  },
  {
    email: "email@mail.com",
    name: "User B54g45gah",
    msg: "Hello There",
    status: "online",
  },
];
